name: ml_env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy=1.24.3
  - pandas>=2.0
  - scikit-learn>=1.3
  - matplotlib>=3.7
  - jupyter
  - ipykernel
  - tqdm
  - pillow
  - requests
  - pip:
    - torch==2.1.0
    - torchvision==0.16.0
    - torchaudio==2.1.0
    - huggingface-hub==0.17.3
    - transformers==4.35.0
    - accelerate==0.24.1
    - tokenizers<0.15,>=0.14
    - datasets
    - evaluate